"""
app/routers/nutrition.py
-------------------------
FastAPI router for nutrition endpoints.
All data is AI-generated by Claude via the Anthropic API — fresh every request.
"""

from fastapi import APIRouter, HTTPException
from typing import Optional
from app.services.nutrition_service import get_recipes, get_meal_plan, get_healthy_swaps

# NO prefix here — main.py already mounts at /api/nutrition
router = APIRouter(tags=["nutrition"])


# GET /api/nutrition/recipes?goal=weight_loss&restrictions=Vegan,Gluten-Free
@router.get("/recipes")
async def recipes_endpoint(goal: str, restrictions: Optional[str] = ""):
    try:
        dietary = [r.strip() for r in restrictions.split(",") if r.strip()] if restrictions else []
        data = get_recipes(goal, dietary)
        return {"recipes": data}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate recipes: {str(e)}")


# GET /api/nutrition/meal-plan?goal=weight_loss&restrictions=&days=7
@router.get("/meal-plan")
async def meal_plan_endpoint(goal: str, restrictions: Optional[str] = "", days: int = 7):
    try:
        dietary = [r.strip() for r in restrictions.split(",") if r.strip()] if restrictions else []
        data = get_meal_plan(goal, dietary, days)
        return {"meal_plan": data}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate meal plan: {str(e)}")


# GET /api/nutrition/healthy-swaps?craving=sweet
@router.get("/healthy-swaps")
async def healthy_swaps_endpoint(craving: str):
    try:
        data = get_healthy_swaps(craving)
        return {"swaps": data}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate swaps: {str(e)}")


# GET /api/nutrition/goals
@router.get("/goals")
async def list_goals():
    return {
        "goals": [
            {"value": "weight_loss",  "label": "Weight Loss"},
            {"value": "weight_gain",  "label": "Weight Gain"},
            {"value": "maintenance",  "label": "Maintenance"},
            {"value": "muscle_gain",  "label": "Muscle Gain"},
        ]
    }


# GET /api/nutrition/cravings
@router.get("/cravings")
async def list_cravings():
    return {
        "cravings": [
            {"value": "sweet",     "label": "Sweet 🍭"},
            {"value": "salty",     "label": "Salty 🧂"},
            {"value": "crunchy",   "label": "Crunchy 🥨"},
            {"value": "creamy",    "label": "Creamy 🥛"},
            {"value": "chocolate", "label": "Chocolate 🍫"},
            {"value": "fried",     "label": "Fried 🍟"},
        ]
    }